### ISSUE TITLE
Meta ticket for running gci on Kubernetes

### ISSUE THREAD

**Issue by arschles** [arschles/gocons#37]
GCI can run on Kubernetes now as long as the Docker socket is mounted, but it's not very useful. Here are some things that would make it more so
- [ ] An API server that lets you submit a tarball to be un-tarred and built & tested (#35, #44)
  - The server should allow the client to send all, or pieces, of a `gci.yaml` file in the request body. Example use cases:
    - They don't have a `gci.yaml` and want to do a `cross-compile`
    - They have a `gci.yaml` but want to override `output-binary`
- [ ] A facility to run appropriate tasks in different pods, rather than containers. This has a few considerations:
  - The new pod will have to stream logs back to the origin server. We could use the Kubernetes logs API for this, or possibly have the new pod open a websocket connection back to the requesting pod, and stream logs that way
  - If the target produces an artifact, like `build`, there will need to be a mechanism for returning it back to the GCI process that submitted it. We could use s3 for this, or maybe have the new pod POST the completed artifact to the requesting pod when it's done
- [ ] The ability to run builds based in response to Github webhooks
  - This includes authentication, which may imply a UI. Here be dragons
- [ ] The ability to resolve dependencies. Here are some dependency management systems I think we should support
  - [glide](https://github.com/Masterminds/glide) (see https://github.com/arschles/gbs/pull/28 for inspiration)
  - [godep](https://github.com/tools/godep)

**Comment by arschles** [comment]
closing as gci doesn't run a server anymore
